version: '3'

services:


  web:
    image: bigmeel94/myapp_web:prod
    ports:
      - "80:3000"
    env_file:
      - .env/production/database
      - .env/production/web
    depends_on:
      - database
    deploy:
      replicas: 2

  db-migrator:
    image: bigmeel94/myapp_web:prod
    command: ["bin/rails", "db:migrate"]
    env_file:
      - .env/production/database
      - .env/production/web
    depends_on:
      - database
    deploy:
      restart_policy:
        condition: on-failure

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

  redis:
    image: redis

  database:
    image: postgres
    env_file:
      - .env/production/database
    volumes:
      - db_data:/var/lib/postgresql/data
  

volumes:
  db_data:
